import React, { useState } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios';
import styles from '../styles/Home.module.css'

type ItemProps = {
  Item:Item;
}

type Item = {
  author: string;
}

const Home: NextPage = () => {
  const [value, setValue] = useState("");
  const [items, setItems] = useState<ItemProps>();
  const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setValue(event.target.value);
  }
  const getData = async(event: React.ChangeEvent<HTMLTextAreaElement>) => {
    event.preventDefault();
    if(value === "") return
    axios.get(`https://app.rakuten.co.jp/services/api/BooksBook/Search/20170404?format=json&author=${value}&applicationId=1072654786515788128`)
    .then(res => {
      const datas = res.data.Items;
      console.log(datas);
      setItems(datas);
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={getData}>
          <input type="text" value={value} onChange={handleChange} />
          <input type="submit" value="送信" />
        </form>
        {items ? items.map((item:ItemProps, id: number) => (
          <div key={id}>
            <h1>{item.Item.author}</h1>
          </div>
        )):
        <h1>検索結果なし</h1>
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
